### ISSUE TITLE
shuffle 

### ISSUE THREAD

**Issue by kingangmar** [Chirmaya/BooruSlideshow#23]
a shuffle option would be awesome to have.

**Comment by throwingfar** [comment]
definitely support this concept. if it's possible.

**Comment by DArrigoni** [comment]
Only way I can imagine doing a real shuffle would be pulling the whole result set and shuffling that, which would be prohibitive for large result sets. Searching for all of `touhou` or something like that. 

Not sure if any of the sites support some kind of random order option, although I doubt it because the client would need to call back with a search key that could recreate the search "random" search order in order to get the next page.

Would like this feature too but the limitation would be shuffling based on what's already loaded, which seems to be a lackluster approach.
